### PR TITLE
added grunt

### PR DESCRIPTION
**Pull request by psullivan6**
**Pull request summary:**
This repo has grunt installed so `grunt adicio`, `grunt legacy`, or other commands can be run to quickly spit out all the necessary template files for each 3rd party. In order to achieve this the main `index.html` file has been separated into includes
- separated all files into includes
- ran grunt build for adicio and legacy

### CODE REVIEW

**Comment by mhulse** [comment]
Interesting! Thanks for help! :)

I just have a few comments before pulling this in:
1. You'll have to give me a demo of this ... Sounds like a cool workflow.
2. We'll want to make sure all node modules get ignored. I have not looked closely, but it looks like your `.gitignore` isn't properly excluding the `node_modules` folder.
3. In future, it's totally cool with me if you work directly on this repo (no need to fork it). If you're worried about effing things up, I highly recommend that we create a `develop` branch, and use that as the test area. In fact, there's no limit to the number of branches we can create, so you could even create a `develop-patrick` branch ... whatever is most comfortable to you.
4. What are you thoughts on using Drone as a sub-module? I'm open to have a grunt build that takes care of the various 3rd parties (that's an interesting way to tackle such things) ... Just wondering if you gave thought to pulling drone into other repos as a sub-module and going from there? I really like the idea of using Grunt to different builds for the various 3rd parties, but would it be more managable in long run for us to dedicate a repos for each 3rd party template/theme? Kinda like sub-themes of Drone, where drone is a submodule?
5. If not repos, what about branches? Maybe we could organize 3rd party variations using branches of Drone?

Anyway, at very minimum, let's ignore those gitmodules. :)

Oh, in future, and this is not documented (but I've been meaning to): When forking, what a lot of people suggest is to create a new branch on your fork, from there you do a pull request asking to merge your fork's branch back into `master`. In the past, I've had some headaches pulling `master` of a fork back into `master` of the main repo. I think it's supposed to be cleaner (or, easier on main repo author) to not work on `master` via your forked version of the code.

**Comment by mhulse** [comment]
For ideas on forking/branching/pulling and contributing, check out:

https://github.com/registerguard/gh-boiler/issues/24

See the section about "contributing".

I've been meaning to add that info to my gh-boiler repository.

**Comment by psullivan6** [comment]
**2.** Donezo.

**3.** Good point, probably easier to do another branch

**4.** That's a good idea. Only real goal was the separation of the code into a bunch of include files that could then get reassembled different ways for each different 3rd party. If the main drone repo was made up of all these include files then the grunt build in each 3rd party repo could use them just fine.

**5.** Another good idea.

Perhaps table all this until our scarce occurrences of the geek meeting or just pow-wow to chat it out some time?

Thanks for the linkage, that helps!

**Comment by mhulse** [comment]
> If the main drone repo was made up of all these include files then the grunt build in each 3rd party repo could use them just fine.

Yah, that was my original goal. I jsut haven't had time to circle back around.

This is aslo the goal with Bulldog repo i.e. make it useful as a submodule where other repos can use the parts to create their own grunt builds.

Do you think you can convert what you've done here to make it so Drone could be a useful submodule in another repo?

> Perhaps table all this until our scarce occurrences of the geek meeting or just pow-wow to chat it out some time?

That'd be cool with me.

I'd love to see what you come up with for a submodule setup on Drone. We could use that as a pattern for Bulldog.

The alternative to submodules, and local dev, would be to symlink another repo like I've done with:

https://github.com/mhulse/bueller#theme

There are definite advantages and disadvantages to submodules. Using a simple symlink might work better. It's definitely something to explore.

**Comment by psullivan6** [comment]
> Do you think you can convert what you've done here to make it so Drone could be a useful submodule in another repo?

Easy-peasy, I just clean out a bunch of stuff, the guts are already there : ) "Marketplaces" repo can cover the adicio code, then just need to create one for Legacy, etc... as those projects get assigned

**Comment by psullivan6** [comment]
Alrighty, I think this latest commits set 'er up fairly nicely. @mhulse I'll defer to you for any further comments and/or the green light to merge : )

**Comment by mhulse** [comment]
@psullivan6 

> Alrighty, I think this latest commits set 'er up fairly nicely. @mhulse I'll defer to you for any further comments and/or the green light to merge : )

Looking good! Nice work.

Before giving green light, just one comment and one question:

### Comment:

In future, feel free to pull/push to this repo directly. It's not a big deal for you to fork and do pull requests, but I think it will be easier on you to work directly on repos.

Like me, If you are concerned about effing things up, it's always a good practice to work on a branch like `develop` and eff things up there ... Once you've fixed any issue, you can then merge it back into `master`.

In order to get a github.io web view of a `develop` branch, feel free to merge `develop` into `gh-pages`; by doing so, you could send me a link to a live web view (ofc, it depends on the project). I only mention this, because sometimes it's so much easier to just check out the live view of a `gh-pages` branch than it is for me to download repo and do a build/open XAMPP.

Moral of story, I totally trust you to work directly on repos ... just use new branches (like `develop`) to do tests/work until you're ready to merge it into `master`.

### Question:

How do you envision this repo to work with other repos?

I'm assuming we'd pull this repo, as a submodule, into another repo and use the pieces to build a version of this theme for other projects?

~~Do you have an example of another repo that's using this theme? If so, do you have a demo page? I'm just curious how this is going to work (I have an idea, it would just be nice to see it working in the real world).~~

Maybe we should just merge your pull request and then you could show me a demo of how this will work, as a submodule, in other repos?

---

Thanks again! This is great! :)

**Comment by mhulse** [comment]
Let's go ahead and merge this pull request. Do you want to press the big green button or should I? :laughing:

**Comment by mhulse** [comment]
> @psullivan6 merged commit `301995f` into `registerguard:master` from `psullivan6:master` 2 minutes ago

Woot woot!

**Pull request merged**
